name: Tests

on:
  push:
    branches: 
        - main
      - name: build SVN
        run: |
          npm run build 
          svn rm *
          svn update
          svn update
          echo "Finish"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          npm install
      - name: Test
        run: |
          npm run test:unit
          
