name: Tests

on:
  push:
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          npm ci
      - name: Test
        run: |
          npm run test:unit